Added snake game sample
raylib-rs/raylib-rs pull request #111
Opened 2024-12-18 11:04 UTC by largenumberhere

I am contributing my snake game as a sample. Looking forward to your feedback, thanks.

2024-12-18 19:59 UTC, IoIxD requested changes
There shouldn't be a "recommended Cargo.toml", this should just be runnable from the examples directory in the same way that all the other examples are.

The code in general needs to be cleaned up, several unused imports/functions. GameState::new_with_snake is the only one thats called as opposed to GameState:;new, it could be merged, and on that note why does snake have a generic for its max size if its always going to be created with the max size anyways?

2024-12-30 18:08 UTC, TSnake41 commented on samples/snake.rs
> +    cmake = "0.1"
Why would a cmake build-dependency be needed here ?

2025-04-14 22:28 UTC, K1ngjulien reviewed
neat :) needs a bit of work tho to be a good example i suppose

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +    let mut draw = rl.begin_drawing(thd);
Careful There! You're drawing a new frame every time you call this/when this value gets dropped.

After looking closely, it seem to work  in your case since its the only drawing done in the `LOST` and `PAUSED` state.

Consider passing a `draw: &mut RaylibDrawHandle` instead of the separate `rl: &mut RaylibHandle` and `thd: &mut RaylibThread`

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +                    // drop(draw);
remove commented out code

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +    // rl.set_target_fps(30);
commented out code

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +    fn add_direction(&mut self, direction: Direction) {
consider renaming to `move_direction` or just `move`, since that's what it does. even says so in the comment :)

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +    cmake = "0.1"
+1 on this being unnecessary

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +struct Position<const MAX: usize> {
why is `MAX` so special it needs const generics?

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +struct Snake<const POS_MAX: usize> {
same as with `Position`

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +    fn reset(&mut self, snake: &mut Snake<{Self::MAP_MAX}>) {
`<{Self::MAP_MAX}>` as mentioned above, not really necessary

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +        const MIN: usize = 0;
ah ok heres the `MIN` to the `MAX` generic argument? consider combining these two, but not in a generic

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +    cells: [[GameCell; 10]; 10],
if you really wanted const generics, these `10`s would be a place where this could make sense like 

```rust
struct GameMap<const WIDTH: usize, const HEIGHT: usize> {
    cells: [[GameCell; WIDTH]; HEIGHT],
    ...
```
but as said, its rather overkill for a snake game :D

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +            panic!("No room on map to place food");
if you're good enough to cover the entire map, you get rewarded with a panic 😂

2025-04-14 22:28 UTC, K1ngjulien commented on samples/snake.rs
> +            let mut empties = Vec::with_capacity(Self::MAP_MAX * Self::MAP_MAX);
probably unnecessary

2025-05-06 11:44 UTC, largenumberhere commented
Hi everyone, thanks so much for all the feedback. I’ve implemented the requested changes - please let me know if anything else needs to be updated. Thanks again.

2025-05-11 04:23 UTC, IoIxD approved these changes

2025-05-11 04:23 UTC, merged