The 5.0.0 update.
raylib-rs/raylib-rs pull request #15
Opened 2024-01-31 19:57 UTC by IoIxD

Opening this PR for a discussion on what needs to be done to finish the 5.0.0 ings. Many of this is going off of [changes in raylib.h since 5.0.0 that have not already been added] and [what isn't visible when comparing to deltaphc/master]

- [ ] `update_camera` gets `mode: i32` and passes it right to the function. This should be changed to just take an actual `CameraMode` as the argument. 
- [ ] `get_random_value` should take a range instead of two `min` and `max` arguments.
- [ ] `ToggleBorderlessWindowed`
- [ ] `SetWindowMonitor`
- [ ] `SetWindowMaxSize`
- [ ] `SetWindowFocused`
- [ ] `EnableEventWaiting`
- [ ] `DisableEventWaiting`
- [ ] `BeginShaderMode`
- [ ] `EndShaderMode`
- [ ] `BeginBlendMode`
- [ ] `EndBlendMode`
- [ ] `BeginVrStereoMode`
- [ ] `EndVrStereoMode`
- [ ] `LoadVrStereoConfig`
- [ ] `UnloadVrStereoConfig`
- [ ] `LoadShaderFromMemory`
- [ ] `IsShaderReady`
- [ ] `LoadModelAnimations`; 
- [ ] `UpdateModelAnimation`; 
- [ ] `UnloadModelAnimation`; 
- [ ] `UnloadModelAnimations`; 
- [ ] `IsModelAnimationValid`; 
- [ ] `SwapScreenBuffer`; 
- [ ] `PollInputEvents`; 
- [ ] `WaitTime`; 
- [ ] `LoadRandomSequence`; 
- [ ] `UnloadRandomSequence`; 
- [ ] `SetLoadFileDataCallback`; 
- [ ] `SetSaveFileDataCallback`; 
- [ ] `SetLoadFileTextCallback`; 
- [ ] `SetSaveFileTextCallback`; 
- [ ] `ExportDataAsCode`; 
- [ ] `GetFileLength`; 
- [ ] `GetApplicationDirectory`; 
- [ ] `IsPathFile`; 
- [ ] `LoadDirectoryFiles`; 
- [ ] `LoadDirectoryFilesEx`; 
- [ ] `UnloadDirectoryFiles`; 
- [ ] `EncodeDataBase64`; 
- [ ] `DecodeDataBase64`; 
- [ ] `LoadAutomationEventList`; 
- [ ] `UnloadAutomationEventList`; 
- [ ] `ExportAutomationEventList`; 
- [ ] `SetAutomationEventList`; 
- [ ] `SetAutomationEventBaseFrame`; 
- [ ] `StartAutomationEventRecording`; 
- [ ] `StopAutomationEventRecording`; 
- [ ] `PlayAutomationEvent`; 
- [ ] `IsKeyPressedRepeat`
- [ ] `GetKeyPressed`
- [ ] `GetCharPressed`
- [ ] `SetGamepadMappings`
- [ ] `UpdateCameraPro`
- [ ] `SetShapesTexture`
- [ ] `DrawCircleSector`
- [ ] `DrawCircleSectorLines`
- [ ] `DrawCircleLinesV`
- [ ] `DrawRing`
- [ ] `DrawRingLines`
- [ ] `DrawRectangleLinesEx` takes float over int now
- [ ] `DrawRectangleRoundedLines` takes float over int now
- [ ] `DrawPolyLinesEx`
- [ ] `DrawSplineLinear`; 
- [ ] `DrawSplineBasis`; 
- [ ] `DrawSplineCatmullRom`; 
- [ ] `DrawSplineBezierQuadratic`; 
- [ ] `DrawSplineBezierCubic`; 
- [ ] `DrawSplineSegmentLinear`; 
- [ ] `DrawSplineSegmentBasis`; 
- [ ] `DrawSplineSegmentCatmullRom`; 
- [ ] `DrawSplineSegmentBezierQuadratic`; 
- [ ] `DrawSplineSegmentBezierCubic`; 
- [ ] `GetSplinePointLinear`; 
- [ ] `GetSplinePointBasis`; 
- [ ] `GetSplinePointCatmullRom`; 
- [ ] `GetSplinePointBezierQuad`; 
- [ ] `GetSplinePointBezierCubic`; 
- [ ] `CheckCollisionPointPoly`; 
- [ ] `CheckCollisionPointLine`; 
- [ ] `LoadImageSvg`
- [ ] `IsImageReady`
- [ ] `ExportImageToMemory`
- [ ] `GenImageGradientLinear`
- [ ] `GenImageGradientSquare`
- [ ] `GenImageText`
- [ ] `ImageBlurGaussian`
- [ ] `ImageRotate`
- [ ] `GetImageColor`
- [ ] `ImageDrawCircleLines`
- [ ] `ImageDrawCircleLinesV`
- [ ] `IsTextureReady`
- [ ] `IsRenderTextureReady`
- [ ] `ColorTint`
- [ ] `ColorBrightness`
- [ ] `ColorContrast`
- [ ] `ColorAlpha`
- [ ] `ColorAlphaBlend`
- [ ] `IsFontReady`
- [ ] `ExportFontAsCode`
- [ ] `DrawTextPro`
- [ ] `DrawTextCodepoints`
- [ ] `SetTextLineSpacing`
- [ ] `GetGlyphInfo`; 
- [ ] `GetGlyphAtlasRec`; 
- [ ] `LoadUTF8`; 
- [ ] `UnloadUTF8`; 
- [ ] `LoadCodepoints`; 
- [ ] `UnloadCodepoints`; 
- [ ] `GetCodepointCount`; 
- [ ] `GetCodepoint`; 
- [ ] `GetCodepointNext`; 
- [ ] `GetCodepointPrevious`; 
- [ ] `CodepointToUTF8`; 
- [ ] Remove `DrawCubeTexture`
- [ ] `DrawCylinderEx`
- [ ] `DrawCylinderWiresEx`
- [ ] `DrawCapsule`
- [ ] `DrawCapsuleWires`
- [ ] Remove `DrawGizmo`
- [ ] `IsModelReady`
- [ ] `DrawBillboardPro`
- [ ] `UploadMesh`
- [ ] `UpdateMeshBuffer`
- [ ] `DrawMesh`
- [ ] `DrawMeshInstanced`
- [ ] `ExportMesh`
- [ ] `GetMeshBoundingBox`
- [ ] `GenMeshTangents`
- [ ] `GetMasterVolume`
- [ ] `IsWaveReady`
- [ ] `LoadSoundAlias`
- [ ] `IsSoundReady`
- [ ] `UpdateSound`
- [ ] `UnloadSoundAlias`
- [ ] `SetSoundPan`
- [ ] `LoadMusicStreamFromMemory`
- [ ] `SeekMusicStream`
- [ ] `SetMusicPan`
- [ ] `InitAudioStream` -> `LoadAudioStream`
- [ ] `IsAudioStreamReady`
- [ ] `SetAudioStreamPan`
- [ ] `SetAudioStreamCallback`
- [ ] `AttachAudioStreamProcessor`
- [ ] `DetatchAudioStreamProcessor`
- [ ] `AttachAudioMixedProcessor`
- [ ] `DetatchAudioMixedProcessor`

2024-03-29 17:01 UTC, Dacode45 requested changes

2024-03-29 18:55 UTC, IoIxD commented on raylib-sys/build.rs
> +const LATEST_RAYLIB_VERSION: &str = "4.2.0";
I actually caught this yesterday and fixed it in #31.

2024-03-29 18:56 UTC, IoIxD commented on raylib-sys/build.rs
> +        .define("CMAKE_BUILD_TYPE", profile)
In the (admittedly rare, but not 0%) chance that one needs to use a regular debugger like gdb, then it makes sense to have the debug symbols avaliable.

2024-03-29 18:59 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
Disagree, if audio cannot be initialized properly it could indicate that the user has no sound, in which case the game can still function, and the programmer should have the option to make the game still run.

2024-03-29 19:03 UTC, IoIxD commented on raylib/src/core/callbacks.rs
> +    fn sprintf(fmt: *const c_char, ...) -> c_int;
Not if we want to be able to use the varargs that are supplied to the callback function.

2024-03-29 19:04 UTC, IoIxD commented on raylib/src/core/callbacks.rs
> +            unsafe { sprintf(buf.as_mut_ptr(), text, args) };
That's what I tried originally and it did not work. Will try again when i have the chance.

2024-03-29 19:05 UTC, IoIxD commented on raylib/src/core/mod.rs
> -        if IS_INITIALIZED.load(Ordering::Relaxed) {
Because Raylib has a built in function for checking if the engine is initialized, `IsWindowReady`, making this unnecessary.

2024-04-04 00:32 UTC, IoIxD commented on raylib/src/core/math.rs
> +    pub struct RayCollision {
RayHitInfo was renamed to RayCollision in 4.2, meaning this is correct.

2024-04-04 00:34 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    pub fn ready(&self) -> bool {
Solved in #31

2024-04-04 00:41 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    pub fn init_audio_device() -> Result<RaylibAudio, RaylibAudioInitError> {
Fixed in #31

2024-04-04 00:49 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    pub fn init_audio_device() -> Result<RaylibAudio, RaylibAudioInitError> {
Solved in #31

2024-04-04 00:50 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    pub fn export(&self, filename: &str) -> bool {
Solved in #31

2024-04-04 00:50 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    pub fn new_music<'aud>(&'aud self, filename: &str) -> Result<Music<'aud>, String> {
Solved in #31

2024-04-04 00:53 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    pub fn new_wave<'aud>(&'aud self, filename: &str) -> Result<Wave<'aud>, String> {
Solved in #31

2024-04-04 00:53 UTC, IoIxD commented on raylib/src/core/callbacks.rs
> +    fn sprintf(fmt: *const c_char, ...) -> c_int;
Solved in #31

2024-04-04 00:53 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    pub fn play(&self) {
I don't know what I'm supposed to do about this.

2024-04-04 00:54 UTC, IoIxD commented on raylib/src/core/callbacks.rs
> +            unsafe { sprintf(buf.as_mut_ptr(), text, args) };
Solved in #31

2024-05-07 00:14 UTC, Dacode45 commented on raylib/src/core/audio.rs
> +    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
That's fair. Peaceful on this.

2024-05-07 00:15 UTC, Dacode45 commented on raylib-sys/build.rs
> +        .define("CMAKE_BUILD_TYPE", profile)
Fair enough. Peaceful on this.

2024-05-09 02:10 UTC, merged