Finishing up 5.0.0
raylib-rs/raylib-rs pull request #29
Opened 2024-02-27 21:53 UTC by IoIxD

- It was decided that we're not binding the UTF8 type. Rust's &str already supports that. Instead, functions that need codepoints will take a &str and internally handle the codepoints stuff. Functions like "GetCodepointCount", "GetCodepointNext", etc. are just not bound.
- Revamped the Sound system to be more elegant to use while also using RAII guards to ensure that the user does not initialize the audio handle and then drop it while sounds created via it are still active, something which results in silent errors. 
    - Bound SoundAlias.
    - Made it so that creating the audio handle twice gives a runtime error; before it would give a varying error based on the user's audio system.
- Bound `Upload` and `UpdateMeshBuffer` as unsafe functions.
- Updated the comment above `UpdateSound` explaining why it can't really be made safe and what we have to do to base raylib to make it safe.
- Changed `DrawTextEx`
- Bound `DrawTextCodepoints`
- Removed `FontLoadEx` as it makes an incorrect assumption: functions which take NULL for the codepoints value HAVE to have the codepoint count set to 0. Functions which took it now take an Option<&str> instead, and the &str is implicitly converted to the internal codepoints struct.
- Removed the global IS_INITIALIZED variable, it was redundant. ffi::IsWindowReady exists.

2024-03-03 18:38 UTC, TSnake41 commented on raylib/src/core/audio.rs
> +impl<'aud> SoundType for Sound<'aud> {
'aud may be uneeded in that cause, I think you can replace it with a anonymous lifetime parameter like
`impl SoundType for Sound<'_>`

2024-03-03 19:21 UTC, TSnake41 requested changes

2024-03-03 19:21 UTC, TSnake41 commented on raylib/src/core/audio.rs
> +pub struct RaylibAudio<'aud>(PhantomData<&'aud ()>);
While I think it is semantically correct in lifetime terms (RaylibAudio references something outside of Rust world), I don't think it is really needed 

we can do something like :
```rust
impl RaylibAudio {
  fn load_sound<'a>(&'a self) -> Sound<'a> { /* ... */ }

  // Which can be simplified with lifetime elision : https://doc.rust-lang.org/reference/lifetime-elision.html
  fn load_sound(&self) -> Sound { /* ... */ }
  // or
  fn load_sound(&self) -> Sound<'_> { /* ... */ }
}
```

Without having the need of PhantomData with lifetime (and lifetime parameter on struct).

2024-03-03 19:21 UTC, TSnake41 commented on raylib/src/core/audio.rs
> +        bytes: &Vec<u8>,
`&[u8]` is preferable to `&Vec<u8>`
(`AsRef<[u8]>` is implemented for `Vec<u8>`, `[u8]`, ...)

2024-03-04 17:36 UTC, IoIxD commented on raylib/src/core/audio.rs
> +    fn inner(&self) -> ffi::Sound;
I'm actually not sure why SoundType was even there when we can just remove it. It's unneeded, because as you mentioned, Deref/AsRef exists.

2024-03-17 16:36 UTC, IoIxD commented
Approved offline

2024-03-17 16:36 UTC, merged