macOS related + AsRef<Path> bugfixes
raylib-rs/raylib-rs pull request #33
Opened 2024-04-03 23:49 UTC by mogery

This PR fixes building this branch on macOS.

2024-04-03 23:57 UTC, IoIxD commented
Funny, you literally made this PR right as I was going to myself.

2024-04-03 23:59 UTC, mogery commented
> Funny, you literally made this PR right as I was going to myself. Was just about to push it when I saw this.

Heh. It's 2AM and my game isn't building, I'm too deep in the zone not to submit a patch :D

2024-04-04 00:01 UTC, IoIxD commented on raylib/src/core/callbacks.rs
The va_list_tag stuff is actually being voided entirely by #31. This is my own PR, so I was waiting to get approval to merge it.

I'm obviously biased in favor of my own solution, but I also realized while doing my PR that there needs to be C code written anyways, because there's a whole plethera of issues with using sprintf/__va_list_tag and, as far as I can tell, there is no way to work around this natively within Rust until they stabilize varargs in extern functions.

2024-04-04 00:04 UTC, IoIxD commented on raylib/src/core/automation.rs
I was actually gonna remove the `impl AsRef` from load_automation_event_list entirely because combining it with Option makes the function very inconvenient to use (raylib-test would actually error out due to the passing of None needing type annotations)

2024-04-04 00:05 UTC, IoIxD requested changes
See comments

2024-04-04 00:06 UTC, mogery commented on raylib/src/core/callbacks.rs
Makes sense. I don't know the timeline on merging that PR, maybe let's get this one in as a temporary fix? Although I'm building off of my repo for now anyways so it's not breaking anything for *me* per se

2024-04-04 00:16 UTC, IoIxD commented on raylib/src/core/callbacks.rs
Sounds good.

2024-04-04 00:17 UTC, mogery commented on raylib/src/core/automation.rs
ooh yeah that's unfortunate. will fix tomorrow morning

2024-04-04 00:19 UTC, IoIxD commented on raylib/src/core/automation.rs
Gonna go ahead and fix it myself, actually, don't worry.

2024-04-04 00:26 UTC, merged