impl from and into Vector2 <-> [f32;2]
raylib-rs/raylib-rs pull request #87
Opened 2024-09-21 17:55 UTC by shivergrass

qol, conversion for Vector2 <-> [f32; 2]

2024-10-24 17:47 UTC, IoIxD requested changes
I'm feel like the From impl might be beyond the point of being acceptably implicit. I'm open to disagreements but I feel like if a function takes a Vector2, then idomatic Rust is that you should see when looking at that function that you're passing in a Vector2, not a different type, and there are exceptions within reason (being able to pass a String and &str to the same function, for instance) but I'm not sure if this is one of them. Not closing the issue or rejecting it, just putting this on the table.

But more importantly, if we did accept this, this should be done for all the Vector types.

2024-12-06 10:58 UTC, TSnake41 requested changes
I think Rust prefers From for everything including :
`From<Vector2> for [f32; 2]` (instead of Into<[f32; 2]>)

2024-12-06 11:02 UTC, TSnake41 commented
> I'm feel like the From impl might be beyond the point of being acceptably implicit. I'm open to disagreements but I feel like if a function takes a Vector2, then idomatic Rust is that you should see when looking at that function that you're passing in a Vector2, not a different type, and there are exceptions within reason (being able to pass a String and &str to the same function, for instance) but I'm not sure if this is one of them. Not closing the issue or rejecting it, just putting this on the table.
> 
> But more importantly, if we did accept this, this should be done for all the Vector types.

Perhaps it should be as a separate function (e.g `Vector2::into_array` ? Or as a `AsRef<[f32; 2]>` but that would require the use of transmute...

2024-12-06 16:55 UTC, IoIxD commented
>Or as a `AsRef<[f32; 2]>` but that would require the use of transmute...

And recently I learned Rust structs do not have a guaranteed layout, and as this has more then one field, it'd be risky.

2024-12-06 20:34 UTC, TSnake41 commented
> > Or as a `AsRef<[f32; 2]>` but that would require the use of transmute...
> 
> And recently I learned Rust structs do not have a guaranteed layout, and as this has more then one field, it'd be risky.

Ah yes Indeed, I though `Vector2` was `repr(C)`

2024-12-06 21:39 UTC, IoIxD commented
Yeah no all the Vector stuff is rewritten in Rust; something which I've been iffy about since I joined the project but that's a seperate discussion lol.

2025-02-14 04:42 UTC, IoIxD commented
Closing due to inactivity from the OP. Feel free to comment if you want us to reopen this.

2025-02-14 04:42 UTC, closed without merging